apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-hello-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-hello
  template:
    metadata:
      labels:
        app: java-hello
    spec:
      containers:
        - name: java-hello-container
          image: kireeti1234/java-hello-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
